### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by zjy359** [ozendelait/wilddash_scripts#1]
Hello!

Thank you very much for your RailSem19-dataset, which is very helpful to my research. Now I want to ask you two questions. First, if I want to add new categories to the RailSem19-dataset, what should I do? Second, I want to use my own original image data to create the same RailSem19-dataset as the dataset. What tools or methods should I use?

I look forward to your reply! Thank you very much for your contribution.

**Comment by ozendelait** [comment]
Hi, please see the associated paper regarding the methodology on how we created RailSem19:
http://openaccess.thecvf.com/content_CVPRW_2019/papers/WAD/Zendel_RailSem19_A_Dataset_for_Semantic_Rail_Scene_Understanding_CVPRW_2019_paper.pdf
If you are interested in the topic of merging/extending existing datasets with other categories: please see https://github.com/ozendelait/rvc_devkit for hints on where to begin
